AY2425S1-CS2103T-F10-4/tp

- docs/AboutUs.md
> Update AboutUs to include my information

- docs/DeveloperGuide.md
Update the use case in Developer Guide
Modify the DeveloperGuide.md, and change the original use case, add more use cases
> Update Developer Guide Use Case

- docs/DeveloperGuide.md
Update DG on the following aspects:
- TA
- Value Proposition
- User stories
- Glossary
closes #33 and #35
> Update Developer Guide: TA, Value proposition, User stories and Glossary

- src/main/java/seedu/address/model/person/Person.java
Add a boolean field to indicate if a company is bookmarked.
closes #42
> Add isBookmark field to a company

- src/main/java/seedu/address/model/tag/DifficultyTag.java
- src/main/java/seedu/address/model/tag/SalaryTag.java
Added A new DifficultyTag class with necessary fields and methods but haven't integrated it to the app CLI to be usable yet
closes #39
> Add new DifficultyTag class

- src/main/java/seedu/address/logic/parser/EditCommandParser.java
Change the edit parser to the MVP format
Remove all the command prefix except for the name and phone that should be in the MVP in the EditCommandParser.java
close #41
> Update Edit Parser

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
> Fix find company tests

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/company/CareerPageUrl.java
- src/main/java/seedu/address/model/company/Company.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedCompany.java
- src/main/java/seedu/address/ui/CompanyCard.java
- src/main/resources/view/CompanyListCard.fxml
- src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
- src/test/java/seedu/address/testutil/CompanyBuilder.java
> Add career page url

- docs/UserGuide.md
Update partial user guide, make it more UI/UX friendly.
> Update partial user guide

- docs/UserGuide.md
- src/main/java/seedu/address/model/company/NameContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/tag/DifficultyTag.java
- src/main/java/seedu/address/model/tag/PeriodTag.java
- src/main/java/seedu/address/model/tag/SalaryTag.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/model/tag/TagBuilder.java
- src/main/java/seedu/address/model/tag/WorkLifeBalanceTag.java
- src/main/java/seedu/address/model/tag/enums/InternshipPeriod.java
- src/main/java/seedu/address/model/tag/enums/Level.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedCompany.java
- src/main/java/seedu/address/storage/JsonAdaptedTag.java
- src/test/java/seedu/address/model/tag/TagBuilderTest.java
- src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
- src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalCompanies.java
- Created Period Tag and WLB Tag
- Mini refactoring of existing tests to suit companies with tags
- Minor changes to JSONAdaptedTags constructor in order for it to work with the new Tag class changes
- Added tests for building Tags via TagBuilder
- Added ability to search for tags via Find Command
closes #73
> Tag feature

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/testutil/CompanyUtil.java
Fix all test cases problem, remove all annotate disabled.
close #75
> Branch fix test cases

- docs/diagrams/ArchitectureSequenceDiagram.puml
- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/DeleteSequenceDiagram.puml
- src/main/java/seedu/address/model/AddressBook.java
Update some UML diagram to suit our project.
close #85
> Update UML Diagram

- docs/UserGuide.md
- docs/diagrams/AppicationStatusSequenceDiagram.puml
> Update UG and diagrams

- build.gradle
- src/main/java/seedu/address/logic/commands/ApplicationStatusCommand.java
- src/main/java/seedu/address/logic/commands/BookmarkCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/RemoveBookmarkCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ApplicationStatusCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/company/ApplicationStatus.java
- src/main/java/seedu/address/model/company/Company.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedCompany.java
- src/main/java/seedu/address/ui/CompanyCard.java
- src/main/resources/view/CompanyListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
- src/test/java/seedu/address/logic/commands/ApplicationStatusCommandTest.java
- src/test/java/seedu/address/logic/commands/BookmarkCommandTest.java
- src/test/java/seedu/address/logic/commands/BookmarkListCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/RemoveBookmarkCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ApplicationStatusCommandParserTest.java
- src/test/java/seedu/address/model/company/CompanyTest.java
- src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
- src/test/java/seedu/address/testutil/CompanyBuilder.java
This pull request creates a new application status command
Command format: status [COMPANY_INDEX] /ap [STATUS]
Closes #87
> Add application status

- src/main/java/seedu/address/logic/Messages.java
> Add url to feedback message

- src/main/java/seedu/address/logic/commands/ApplicationStatusCommand.java
- src/main/java/seedu/address/model/company/UniqueCompanyList.java
- src/main/java/seedu/address/ui/CompanyCard.java
- src/main/resources/view/CompanyListCard.fxml
> Update UI on application status command execute

- src/main/java/seedu/address/model/company/Name.java
- src/test/java/seedu/address/model/company/CompanyTest.java
Update the cases such that if 2 company have the same name but in different cases, they are consider the same company.
close #111
> Update Company Duplicate Name

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/RemarkCommand.java
- src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Add remark and application status to feedback message
close #112 
close #115
> Update feedback message

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/ApplicationStatusCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/RemarkCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/company/ApplicationStatus.java
- src/main/java/seedu/address/model/company/Remark.java
- src/main/java/seedu/address/ui/CompanyCard.java
- src/main/resources/view/CompanyListCard.fxml
- src/main/resources/view/DarkTheme.css
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
Update the overall UI, change the default representation of applicationStatus and remark, add the label field to every label, add the remark to the UI
close #135 
close #136 
close #140
> Update the Overall UI

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
Fix message usage to fit the current app
Commands affected:
- Add command
- Find command
close #98
close #99
close #108
> Fix message usage in commands

- src/test/java/seedu/address/model/company/RemarkTest.java
Add the test cases for Remark
close #149
> Add Remark test cases

- docs/DeveloperGuide.md
> Update DeveloperGuide to make it more relevant

- docs/UserGuide.md
closes #192 
closes #203 
closes #225 
closes #224 
closes #181
> Update UG specific to remark command

- docs/UserGuide.md
> Update minor changes to UG
